apiVersion: v1
kind: Pod
metadata:
  name: bob-false
  namespace: bob
spec:
  containers:
    - name: bob
      image: "jupyter/datascience-notebook"
      resources:
        limits:
          cpu: "100m"
          memory: "30Mi"
