apiVersion: v1
kind: Pod
metadata:
  name: alice-true
  namespace: alice
spec:
  containers:
    - name: alice
      image: "k8scc01covidacr.azurecr.io/sas:452"
      resources:
        limits:
          cpu: "100m"
          memory: "30Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: alice-false
  namespace: alice
spec:
  containers:
    - name: alice
      image: "jupyter/datascience-notebook"
      resources:
        limits:
          cpu: "100m"
          memory: "30Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: bob-false
  namespace: bob
spec:
  containers:
    - name: bob
      image: "jupyter/datascience-notebook"
      resources:
        limits:
          cpu: "100m"
          memory: "30Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: sam-true
  namespace: sam
spec:
  containers:
    - name: sam
      image: "jupyter/datascience-notebook"
      resources:
        limits:
          cpu: "100m"
          memory: "30Mi"
    - name: sam-other-container
      image: "k8scc01covidacr.azurecr.io/sas:452"
      resources:
        limits:
          cpu: "100m"
          memory: "30Mi"
