apiVersion: kubeflow.org/v1
kind: Profile
metadata:
  name: alice
spec:
  owner:
    kind: User
    name: alice@external.ca
  resourceQuotaSpec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: alice
---
apiVersion: kubeflow.org/v1
kind: Profile
metadata:
  name: bob
  labels:
    test: "true"
spec:
  owner:
    kind: User
    name: bob@external.ca
  resourceQuotaSpec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: bob
---
apiVersion: kubeflow.org/v1
kind: Profile
metadata:
  name: sam
spec:
  owner:
    kind: User
    name: sam@external.ca
  resourceQuotaSpec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: sam
---