apiVersion: kubeflow.org/v1
kind: Profile
metadata:
  name: alice
spec:
  owner:
    kind: User
    name: alice@external.ca
  resourceQuotaSpec: {}
---
apiVersion: kubeflow.org/v1
kind: Profile
metadata:
  name: bob
  labels: 
    test: "true"
spec:
  owner:
    kind: User
    name: bob@external.ca
  resourceQuotaSpec: {}
---
apiVersion: kubeflow.org/v1
kind: Profile
metadata:
  name: sam
spec:
  owner:
    kind: User
    name: sam@external.ca
  resourceQuotaSpec: {}

