apiVersion: v1
kind: Pod
metadata:
  name: alice-true
  namespace: alice
spec:
  containers:
    - name: alice
      image: "k8scc01covidacr.azurecr.io/sas:452"
      resources:
        limits:
          cpu: "100m"
          memory: "30Mi"
