apiVersion: v1
kind: Pod
metadata:
  name: pod-true
  namespace: bob
spec:
  containers:
    - name: bob
      image: "k8scc01covidacr.azurecr.io/sas:281"
      resources:
        limits:
          cpu: "100m"
          memory: "30Mi"
